version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "suia-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-inke18j7vncf"
s3_prefix = "suia-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
